### ISSUE TITLE
Netlify Build failed

### ISSUE THREAD

**Issue by tomashak** [TuanManhCao/digital-garden#25]
I used your repozitory as a copy with my MD files.
I got this build log with errors:

10:00:56 PM: build-image version: 3b96229e32b19cdf63f20dc1fc9331cd240c2d01 (focal)
10:00:56 PM: buildbot version: 3b96229e32b19cdf63f20dc1fc9331cd240c2d01
10:00:56 PM: Fetching cached dependencies
10:00:56 PM: Failed to fetch cache, continuing with build
10:00:56 PM: Starting to prepare the repo for build
10:00:56 PM: No cached dependencies found. Cloning fresh repo
10:00:56 PM: git clone --filter=blob:none https://github.com/tomashak/obsidian_digital_garden
10:00:56 PM: Preparing Git Reference refs/heads/main
10:00:58 PM: Starting to install dependencies
10:00:58 PM: Python version set to 3.8
10:00:59 PM: Attempting Ruby version 2.7.2, read from environment
10:00:59 PM: Using Ruby version 2.7.2
10:01:00 PM: Started restoring cached go cache
10:01:00 PM: Finished restoring cached go cache
10:01:00 PM: go version go1.19.10 linux/amd64
10:01:01 PM: Using PHP version 8.0
10:01:02 PM: v18.16.0 is already installed.
10:01:03 PM: Now using node v18.16.0 (npm v9.5.1)
10:01:03 PM: Enabling Node.js Corepack
10:01:03 PM: Started restoring cached build plugins
10:01:03 PM: Finished restoring cached build plugins
10:01:03 PM: Started restoring cached corepack dependencies
10:01:03 PM: Finished restoring cached corepack dependencies
10:01:03 PM: Started restoring cached yarn cache
10:01:03 PM: Finished restoring cached yarn cache
10:01:03 PM: No yarn workspaces detected
10:01:03 PM: Started restoring cached node modules
10:01:03 PM: Finished restoring cached node modules
10:01:04 PM: Installing npm packages using Yarn version 1.22.19
10:01:04 PM: yarn install v1.22.19
10:01:04 PM: [1/4] Resolving packages...
10:01:04 PM: [2/4] Fetching packages...
10:01:26 PM: [3/4] Linking dependencies...
10:01:26 PM: warning "@emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
10:01:26 PM: warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
10:01:26 PM: warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
10:01:39 PM: [4/4] Building fresh packages...
10:01:39 PM: Done in 35.16s.
10:01:39 PM: npm packages installed using Yarn
10:01:40 PM: Install dependencies script success
10:01:40 PM: Starting build script
10:01:41 PM: Detected 1 framework(s)
10:01:41 PM: "next" at version "12.1.0"
10:01:41 PM: Section completed: initializing
10:01:42 PM: ​
10:01:42 PM: Netlify Build                                                 
10:01:42 PM: ────────────────────────────────────────────────────────────────
10:01:42 PM: ​
10:01:42 PM: ❯ Version
10:01:42 PM:   @netlify/build 29.12.1
10:01:42 PM: ​
10:01:42 PM: ❯ Flags
10:01:42 PM:   baseRelDir: true
10:01:42 PM:   buildId: 6484d67609e5ab1baf7796b8
10:01:42 PM:   deployId: 6484d67609e5ab1baf7796ba
10:01:42 PM: ​
10:01:42 PM: ❯ Current directory
10:01:42 PM:   /opt/build/repo
10:01:42 PM: ​
10:01:42 PM: ❯ Config file
10:01:42 PM:   No config file was defined: using default values.
10:01:42 PM: ​
10:01:42 PM: ❯ Context
10:01:42 PM:   production
10:01:43 PM: ​
10:01:43 PM: ❯ Installing plugins
10:01:43 PM:    - @netlify/plugin-nextjs@4.37.4
10:01:51 PM: ​
10:01:51 PM: ❯ Using Next.js Runtime - v4.37.4
10:01:53 PM: ​
10:01:53 PM: @netlify/plugin-nextjs (onPreBuild event)                     
10:01:53 PM: ────────────────────────────────────────────────────────────────
10:01:53 PM: ​
10:01:53 PM: No Next.js cache to restore.
10:01:53 PM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
10:01:53 PM: ​
10:01:53 PM: (@netlify/plugin-nextjs onPreBuild completed in 19ms)
10:01:53 PM: ​
10:01:53 PM: Build command from Netlify app                                
10:01:53 PM: ────────────────────────────────────────────────────────────────
10:01:53 PM: ​
10:01:53 PM: $ yarn build
10:01:53 PM: yarn run v1.22.19
10:01:53 PM: $ rm -rf graph-data.json && next build
10:01:54 PM: warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
10:01:54 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
10:01:54 PM: Browserslist: caniuse-lite is outdated. Please run:
10:01:54 PM:   npx browserslist@latest --update-db
10:01:54 PM:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
10:01:54 PM: info  - Checking validity of types...
10:01:54 PM: warn  - No ESLint configuration detected. Run next lint to begin setup
10:01:54 PM: info  - Creating an optimized production build...
10:01:55 PM: Browserslist: caniuse-lite is outdated. Please run:
10:01:55 PM: npx browserslist@latest --update-db
10:01:55 PM: Why you should do it regularly:
10:01:55 PM: https://github.com/browserslist/browserslist#browsers-data-updating
10:02:04 PM: info  - Compiled successfully
10:02:04 PM: info  - Collecting page data...
10:02:06 PM: Error: ENOENT: no such file or directory, lstat '/opt/build/repo/graph-data.json'
10:02:06 PM:     at Object.lstatSync (node:fs:1593:3)
10:02:06 PM:     at Object.isFile (/opt/build/repo/.next/server/chunks/403.js:264:62)
10:02:06 PM:     at constructGraphData (/opt/build/repo/.next/server/chunks/403.js:751:65)
10:02:06 PM:     at /opt/build/repo/.next/server/pages/index.js:69:100 {
10:02:06 PM:   errno: -2,
10:02:06 PM:   syscall: 'lstat',
10:02:06 PM:   code: 'ENOENT',
10:02:06 PM:   path: '/opt/build/repo/graph-data.json'
10:02:06 PM: }
10:02:07 PM: info  - Generating static pages (0/12)
10:02:11 PM: info  - Generating static pages (3/12)
10:02:11 PM: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
10:02:11 PM: Error: ENOENT: no such file or directory, open '/opt/build/repo/posts/index.md'
10:02:11 PM:     at Object.openSync (node:fs:601:3)
10:02:11 PM:     at Object.readFileSync (node:fs:469:35)
10:02:11 PM:     at Object.readFileSync (/opt/build/repo/.next/server/chunks/403.js:290:58)
10:02:11 PM:     at getSinglePost (/opt/build/repo/.next/server/chunks/403.js:704:85)
10:02:11 PM:     at getStaticProps (/opt/build/repo/.next/server/pages/index.js:72:92)
10:02:11 PM:     at renderToHTML (/opt/build/repo/node_modules/next/dist/server/render.js:465:26)
10:02:11 PM:     at async /opt/build/repo/node_modules/next/dist/export/worker.js:269:36
10:02:11 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:75:20)
10:02:11 PM: info  - Generating static pages (6/12)
10:02:11 PM: info  - Generating static pages (9/12)
10:02:12 PM: info  - Generating static pages (12/12)
10:02:12 PM: > Build error occurred
10:02:12 PM: Error: Export encountered errors on following paths:
10:02:12 PM: 	/
10:02:12 PM:     at /opt/build/repo/node_modules/next/dist/export/index.js:498:19
10:02:12 PM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:02:12 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:75:20)
10:02:12 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:1024:17
10:02:12 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:75:20)
10:02:12 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:898:13
10:02:12 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:75:20)
10:02:12 PM:     at async Object.build [as default] (/opt/build/repo/node_modules/next/dist/build/index.js:82:25)
10:02:12 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
10:02:12 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:02:12 PM: ​
10:02:12 PM: "build.command" failed                                        
10:02:12 PM: ────────────────────────────────────────────────────────────────
10:02:12 PM: ​
10:02:12 PM:   Error message
10:02:12 PM:   Command failed with exit code 1: yarn build (https://ntl.fyi/exit-code-1)
10:02:12 PM: ​
10:02:12 PM:   Error location
10:02:12 PM:   In Build command from Netlify app:
10:02:12 PM:   yarn build
10:02:12 PM: ​
10:02:12 PM:   Resolved config
10:02:12 PM:   build:
10:02:12 PM:     command: yarn build
10:02:12 PM:     commandOrigin: ui
10:02:12 PM:     environment:
10:02:12 PM:       - NEXT_PRIVATE_TARGET
10:02:12 PM:     publish: /opt/build/repo/.next
10:02:12 PM:     publishOrigin: ui
10:02:12 PM:   plugins:
10:02:12 PM:     - inputs: {}
10:02:12 PM:       origin: ui
10:02:12 PM:       package: '@netlify/plugin-nextjs'
10:02:13 PM: Caching artifacts
10:02:13 PM: Started saving node modules
10:02:13 PM: Finished saving node modules
10:02:13 PM: Started saving build plugins
10:02:13 PM: Finished saving build plugins
10:02:13 PM: Started saving corepack cache
10:02:13 PM: Finished saving corepack cache
10:02:13 PM: Started saving yarn cache
10:02:16 PM: Finished saving yarn cache
10:02:16 PM: Started saving pip cache
10:02:16 PM: Finished saving pip cache
10:02:16 PM: Started saving emacs cask dependencies
10:02:16 PM: Finished saving emacs cask dependencies
10:02:16 PM: Started saving maven dependencies
10:02:16 PM: Finished saving maven dependencies
10:02:16 PM: Started saving boot dependencies
10:02:16 PM: Finished saving boot dependencies
10:02:16 PM: Started saving rust rustup cache
10:02:16 PM: Finished saving rust rustup cache
10:02:16 PM: Started saving go dependencies
10:02:16 PM: Finished saving go dependencies
10:02:17 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:02:17 PM: Failing build: Failed to build site
10:02:17 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
10:02:17 PM: Finished processing build request in 1m21.644s

**Comment by corvusdeinanis** [comment]
Your repository is missing an `index.md` file. Create one in the posts folder (https://github.com/tomashak/obsidian_digital_garden/tree/main/posts)
